controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 20.0

    base_frame_id: base_footprint

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.208
    wheel_radius: 0.0332

    use_stamped_vel: false

    # open_loop: false    wheel_separation: 0.1966

    # wheels_per_side: x
    wheel_separation_multiplier: 1.00
    left_wheel_radius_multiplier: 1.00
    right_wheel_radius_multiplier: 1.00

    odom_frame_id: odom
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 3.0        # default 1.0
    linear.x.min_velocity: -3.0       # default -1.0
    linear.x.max_acceleration: 2.0    # 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 3.0       # default 1.0
    angular.z.min_velocity: -3.0      # default 1.0
    angular.z.max_acceleration: 2.0   # default 1.0
    angular.z.min_acceleration: -2.0  # default 1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0




# joint_broad:
#   ros__parameters: